### ISSUE TITLE
[NEAR] Deployment

### ISSUE THREAD

**Issue by SuperBatata** [walt-id/waltid-nftkit#76]

**Comment by SuperBatata** [comment]
will need assistance to handle the .env file for production

**Comment by philpotisk** [comment]
> will need assistance to handle the .env file for production

@mikeplotean please jump in here! thanks!

**Comment by philpotisk** [comment]
@SuperBatata please merge everything so the web-wallet can be integrated with https://nftkit.walt-test.cloud/v2/nftkit/swagger
